- name: Ensure /home/backup/mysql directory is created
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: 0744

- name: Grant privileges for user backup
  community.mysql.mysql_user:
    name: backup
    password: "{{ mysql_password }}"
    priv: "*.*:ALL,GRANT"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Template mysql configuration file
  template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: 0744

- name: Template cron file
  template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
  notify: Restart cron
