- name: Install nginx
  apt: 
    name: nginx
    
- name: Replace vm /etc/nginx/sites-enabled/default with nginx configuration as uWSGI frontend
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: 
  - Reload nginx
  - Restart nginx  
    
- name: Ensure nginx service is started unconditionally
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  


  
