- name: Create directory /opt/agama if it does not exist
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    mode: '755'

- name: Install dependencies
  apt:
    name: python3-flask-sqlalchemy

- name: Install agama application 
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    force: yes
    dest: /opt/agama/
    mode: '755'