- name: Create /opt/agama for docker container
  file:
    path: /opt/agama
    state: directory

- name: Download agama for docker container
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Install dependencies
  apt:
    name: python3-flask-sqlalchemy

- name: Build agama.iso on docker
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Create agama-1 container
  community.docker.docker_container:
    name: agama-1
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    published_ports: "{{ agama_port }}:8000"
    #restart_policy: always

- name: Create agama-2 container
  community.docker.docker_container:
    name: agama-2
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    published_ports: "{{ agama_port + 1 }}:8000"
    #restart_policy: always
