---
- name: Install mysql exporter
  apt:
    name: prometheus-mysqld-exporter
  register: prometheus_mysqld_exporter_installed

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10 # method 1

- name: Create /var/lib/prometheus Directory
  file:
    path: /var/lib/prometheus
    state: directory 

- name: template cnf
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify: 
    - Restart mysql
    - Restart mysql_exporter

- name: Pause for 10 sec
  pause:
    seconds: 10
  when: prometheus_mysqld_exporter_installed.changed

- name: Template prometheus-mysqld-exporter
  template:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify: Restart mysql_exporter 

- name: Execute handlers
  meta: flush_handlers

- name: Ensure mysql is started
  service:
    name: mysql
    state: started
    enabled: yes

- name: Ensure mysqld exporter is started
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
