# config file version
apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    url: http://sandr0o-1/prometheus
    editable: true

  - name: influxdb
    type: influxdb
    url: http://sandr0o-2.{{ domainName }}:8086
    database: latency
    editable: true

  - name: influxdb:telegraf
    type: influxdb
    url: http://sandr0o-2.{{ domainName }}:8086
    database: telegraf
    editable: true
