# config file version
apiVersion: 1

datasources:
 - name: prometheus
   type: prometheus
   url: http://prometheus:/prometheus
   isDefault: true
   editable: true

 - name: InfluxDB
   type: influxdb
   url: http://influxdb:8086
   database: latency
   editable: true

 - name: InfluxDB-telegraf
   type: influxdb
   url: http://influxdb:8086
   database: telegraf
   editable: true

